[project]
name = "comfyui-deforum"
description = "Custom nodes for deforum workflows"
version = "0.3.0"
license = { file = "LICENSE.txt" }

[project.urls]
Repository = "https://github.com/deforum-art/deforum-comfy-nodes"

[tool.comfy]
PublisherId = "deforum"
DisplayName = "ComfyUI-Deforum"
Icon = "ğŸ„â€â™‚ï¸"
